#!/bin/bash

___lab6_task1(){

  cat << EOF | ssh $1 "cat > $2"
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-web-server-rs
spec:
    replicas: 5
    selector:
        matchLabels:
            app: rs-app
    template:
        metadata:
            labels:
                app: rs-app
        spec:
            containers:
            -   name: nginx
                image: nginx:1.15.1
                ports:
                - containerPort: 80
EOF

  echo -e "Generate file in [ $1 ] - $2"
}

___lab6_task2(){

  cat << EOF | ssh $1 "cat > $2"
apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-web-server-deploy
spec:
    replicas: 5
    selector:
        matchLabels:
            app: deploy-app
    template:
        metadata:
            labels:
                app: deploy-app
        spec:
            containers:
            -   name: nginx
                image: nginx:1.15.1
                ports:
                - containerPort: 80
EOF

  echo -e "Generate file in [ $1 ] - $2"
}



__TASK_LIST="task1 task2"
__TASK_HELP="Usage: - lab6-help <task1 | task2>"
if [[ $# -eq 0 ]] ; then
      echo "$__TASK_HELP"
      exit 1
elif [[ "$__TASK_LIST" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
      if [[ $1 == "task1" ]]; then
        ___lab6_task1 k8s-cp /home/student/my-web-server-rs.yaml
      elif [[ $1 == "task2" ]]; then
        ___lab6_task2 k8s-cp /home/student/my-web-server-deploy.yaml
      else
        echo "$__TASK_HELP"
        exit 1
      fi 
else
    echo "$__TASK_HELP"
    exit 1
fi

