#!/bin/bash

___lab7_task1(){
 cat << EOF | ssh $1 "cat > $2"
apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip
  labels:
    app: svc-clusterip
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
EOF

  echo -e "Generate file in [ $1 ] - $2"
}

___lab7_task2(){
 cat << EOF | ssh $1 "cat > $2"
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  labels:
    app: svc-nodeport
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
EOF

  echo -e "Generate file in [ $1 ] - $2"
}

__TASK_LIST="task1 task2"
__TASK_HELP="Usage: - lab7-help <task1 | task2>"
if [[ $# -eq 0 ]] ; then
      echo "$__TASK_HELP"
      exit 1
elif [[ "$__TASK_LIST" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
      if [[ $1 == "task1" ]]; then
        ___lab7_task1 k8s-cp /home/student/svc-clusterip.yaml
      elif [[ $1 == "task2" ]]; then
        ___lab7_task2 k8s-cp /home/student/svc-nodeport.yaml
      else
        echo "$__TASK_HELP"
        exit 1
      fi
else
    echo "$__TASK_HELP"
    exit 1
fi
